{{- if .Values.rollout.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "common.fullname" . }}-success-rate
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  metrics:
    - name: webcheck
      interval: {{ .Values.rollout.analysis.interval }}
      count: {{ .Values.rollout.analysis.count }}
      failureLimit: {{ .Values.rollout.analysis.failureLimit }}
      successCondition: result == "healthy"
      provider:
        web:
          url: http://{{ include "common.fullname" . }}.{{ .Release.Namespace }}.svc{{ .Values.rollout.analysis.path }}
          jsonPath: "{$.status}"
{{- end }}
