{{- if eq .Values.rollout.strategy "blueGreen" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-preview
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rollout.blueGreen.previewService.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.rollout.blueGreen.previewService.port }}
      targetPort: {{ .Values.rollout.blueGreen.previewService.targetPort }}
      {{- if and (eq .Values.rollout.blueGreen.previewService.type "NodePort") .Values.rollout.blueGreen.previewService.nodePort }}
      nodePort: {{ .Values.rollout.blueGreen.previewService.nodePort }}
      {{- end }}
{{- end }}
