apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-go
  labels:
    app: devops-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-go
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: devops-go
    spec:
      containers:
        - name: app
          image: s3rap1s/devops-info-service-go:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: HOST
              value: "0.0.0.0"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
