workload:
  type: statefulset

replicaCount: 3

image:
  tag: "lab15"

service:
  type: NodePort
  nodePort: 32150

configFile:
  environment: "statefulset-partition"

configEnv:
  APP_ENV: "statefulset-partition"
  LOG_LEVEL: "debug"

hooks:
  preInstall:
    enabled: false
  postInstall:
    enabled: false

persistence:
  enabled: true
  size: 100Mi
  storageClass: ""
  accessMode: ReadWriteOnce

statefulset:
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    partition: 2
