replicaCount: 1

image:
  tag: "v2"

service:
  type: NodePort

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 3
  periodSeconds: 5

configFile:
  environment: "development"

configEnv:
  APP_ENV: "development"
