nameOverride: ""
fullnameOverride: ""

replicaCount: 3

image:
  repository: s3rap1s/devops-info-service
  tag: "v2"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: null

container:
  port: 5000

env:
  - name: PORT
    value: "5000"
  - name: HOST
    value: "0.0.0.0"

configFile:
  applicationName: "devops-info-service"
  environment: "development"
  settings:
    featureGreeting: true
    maxVisitsDisplay: 10

configEnv:
  APP_ENV: "development"
  LOG_LEVEL: "info"
  FEATURE_GREETINGS: "true"
  DATA_DIR: "/data"
  CONFIG_FILE: "/config/config.json"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5

hooks:
  image: busybox:1.36.1
  preInstall:
    enabled: true
    weight: -5
  postInstall:
    enabled: true
    weight: 5

secret:
  create: true
  username: "user"
  password: "pass"

serviceAccount:
  create: true
  name: ""

vault:
  enabled: false
  role: "devops-python"
  secretPath: "secret/data/myapp/config"

persistence:
  enabled: true
  size: 100Mi
  storageClass: ""
  accessMode: ReadWriteOnce

rollout:
  revisionHistoryLimit: 2
  strategy: canary
  canary:
    maxSurge: 25%
    maxUnavailable: 0
    steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause:
          duration: 30s
      - setWeight: 60
      - pause:
          duration: 30s
      - setWeight: 80
      - pause:
          duration: 30s
      - setWeight: 100
  blueGreen:
    autoPromotionEnabled: false
    autoPromotionSeconds: null
    scaleDownDelaySeconds: 30
    previewReplicaCount: 1
    previewService:
      type: NodePort
      port: 80
      targetPort: 5000
      nodePort: null
  analysis:
    enabled: false
    interval: 10s
    count: 3
    failureLimit: 1
    path: /health
