nameOverride: ""
fullnameOverride: ""

replicaCount: 2

image:
  repository: s3rap1s/devops-info-service-go
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

container:
  port: 5000

env:
  - name: PORT
    value: "5000"
  - name: HOST
    value: "0.0.0.0"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5
